# Generated by Django 3.1.3 on 2020-12-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20201205_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='context',
        ),
    ]
