# Generated by Django 3.1.3 on 2020-12-05 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_faq_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='links',
        ),
    ]
