# Generated by Django 3.1.3 on 2020-12-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_aboutmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aboutmodel',
            new_name='About',
        ),
    ]
