# Generated by Django 3.1.3 on 2020-12-09 14:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='context',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
